CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('OWNER', 'CHEF'))
);

CREATE TABLE restaurant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE dish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    category VARCHAR(255),
    selling_price NUMERIC(12, 2) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_dish_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)
);

CREATE TABLE ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    cost_per_unit NUMERIC(12, 4) NOT NULL,
    current_stock NUMERIC(12, 4) NOT NULL,
    minimum_stock NUMERIC(12, 4) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_ingredient_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT ingredient_unit_check CHECK (unit IN ('GRAM', 'KILOGRAM', 'MILLILITER', 'LITER', 'PIECE'))
);

CREATE TABLE recipe_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity_required NUMERIC(12, 4) NOT NULL,
    CONSTRAINT fk_recipe_item_dish FOREIGN KEY (dish_id) REFERENCES dish (id),
    CONSTRAINT fk_recipe_item_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)
);

CREATE TABLE sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    sale_date DATE NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_sale_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)
);

CREATE TABLE sale_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selling_price NUMERIC(12, 2) NOT NULL,
    dish_cost_at_sale NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sale (id),
    CONSTRAINT fk_sale_item_dish FOREIGN KEY (dish_id) REFERENCES dish (id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL UNIQUE,
    current_quantity NUMERIC(12, 4) NOT NULL,
    last_updated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_inventory_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT fk_inventory_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)
);

CREATE TABLE inventory_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    transaction_type VARCHAR(50) NOT NULL,
    quantity NUMERIC(12, 4) NOT NULL,
    reason VARCHAR(255),
    transaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_inventory_transaction_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient (id),
    CONSTRAINT inventory_transaction_type_check CHECK (transaction_type IN ('PURCHASE', 'SALE_USAGE', 'ADJUSTMENT', 'WASTE'))
);

CREATE TABLE expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    amount NUMERIC(12, 2) NOT NULL,
    expense_date DATE NOT NULL,
    bill_file_url VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_expense_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT expense_category_check CHECK (category IN ('FOOD', 'PACKAGING', 'GAS', 'ELECTRICITY', 'WATER', 'STAFF', 'RENT', 'DELIVERY', 'MEDICAL', 'MAINTENANCE', 'CLEANING', 'MISCELLANEOUS'))
);

CREATE INDEX idx_dish_restaurant_id ON dish (restaurant_id);
CREATE INDEX idx_ingredient_restaurant_id ON ingredient (restaurant_id);
CREATE INDEX idx_recipe_item_dish_id ON recipe_item (dish_id);
CREATE INDEX idx_recipe_item_ingredient_id ON recipe_item (ingredient_id);
CREATE INDEX idx_sale_restaurant_date ON sale (restaurant_id, sale_date);
CREATE INDEX idx_sale_item_sale_id ON sale_item (sale_id);
CREATE INDEX idx_sale_item_dish_id ON sale_item (dish_id);
CREATE INDEX idx_inventory_restaurant_id ON inventory (restaurant_id);
CREATE INDEX idx_inventory_transaction_ingredient_date ON inventory_transaction (ingredient_id, transaction_date);
CREATE INDEX idx_expense_restaurant_date ON expense (restaurant_id, expense_date);
