import { useEffect, useState } from 'react'
import { BrowserRouter, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import axios from 'axios'
import { BarChart3, BookOpen, Boxes, ChefHat, CircleDollarSign, ClipboardList, Gauge, Lightbulb, LogIn, Menu, ReceiptText, Settings2, ShoppingBag, Sparkles, Utensils } from 'lucide-react'
import { AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './App.css'

const api = axios.create({ baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api' })
const restaurantId = import.meta.env.VITE_RESTAURANT_ID || ''
const navigation = [
  ['/dashboard', 'Overview', Gauge], ['/dishes', 'Dishes', Utensils], ['/ingredients', 'Ingredients', Boxes], ['/recipes', 'Recipes', BookOpen], ['/sales', 'Sales', ShoppingBag], ['/inventory', 'Inventory', ClipboardList], ['/expenses', 'Expenses', ReceiptText], ['/profit', 'Profit', CircleDollarSign], ['/analytics', 'Analytics', BarChart3], ['/ai-insights', 'AI insights', Sparkles],
]

export default function App() { return <BrowserRouter><Workspace /></BrowserRouter> }
function Workspace() {
  const [open, setOpen] = useState(false)
}
function Redirect() { const navigate = useNavigate(); useEffect(() => navigate('/dashboard', { replace: true }), [navigate]); return null }
function CurrentLabel() { const path = useLocation().pathname; return <strong>{navigation.find(([to]) => path.startsWith(to))?.[1] || 'Overview'}</strong> }
function PageIntro({ eyebrow, title, description, action }) { return <div className="page-intro"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action && <button className="primary-button"><b>+</b>{action}</button>}</div> }
function Dashboard() { const { data, loading, error } = useDashboardData(); const cards = [['Revenue', data?.totalRevenue, 'currency', 'this period'], ['Expenses', data?.totalExpenses, 'currency', 'this period'], ['Actual profit', data?.actualProfit, 'currency', 'after all costs'], ['Food cost', data?.foodCostPercentage, 'percent', 'of revenue'], ['Low stock', data?.lowStockItems, 'count', 'items need attention']]; return <><PageIntro eyebrow="Friday, 28 August 2026" title="Good morning, Riya" description="Here is how Blue Apron Kitchen is performing today." action="Record sale" />{error && <ApiNotice message={error} />}<section className="metric-grid">{cards.map(([label, value, type, note], i) => <MetricCard key={label} label={label} value={loading ? null : value} type={type} note={note} warning={i === 4} />)}</section><div className="section-heading"><div><h2>Performance snapshot</h2><p>Live financial metrics from the connected API.</p></div><select className="select-control" defaultValue="30"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></div><section className="chart-grid"><ChartPanel title="Revenue vs expenses" subtitle="Series data will appear when the backend provides daily history."><EmptyChart /></ChartPanel><ChartPanel title="Daily profit trend" subtitle="Connect a date-series endpoint to populate this view."><EmptyChart /></ChartPanel></section><div className="section-heading lower-heading"><div><h2>Operating signals</h2><p>Categories returned by your workspace.</p></div></div><section className="chart-grid"><ChartPanel title="Expense breakdown" subtitle="Category totals for the current day."><BreakdownChart data={data?.breakdown || []} /></ChartPanel><ChartPanel title="Dish profitability" subtitle="Historical sale-item costs, when available."><EmptyChart /></ChartPanel></section></> }
function useDashboardData() { const [state, setState] = useState({ loading: true, data: null, error: null }); useEffect(() => { const date = new Date().toISOString().slice(0, 10); if (!restaurantId) { setState({ loading: false, data: null, error: 'Set VITE_RESTAURANT_ID to load live restaurant metrics.' }); return } Promise.all([api.get(`/profitability/daily?restaurantId=${restaurantId}&date=${date}`), api.get(`/profitability/expense-breakdown?restaurantId=${restaurantId}&startDate=${date}&endDate=${date}`)]).then(([summary, breakdown]) => setState({ loading: false, data: { ...summary.data, breakdown: breakdown.data }, error: null })).catch(() => setState({ loading: false, data: null, error: 'The backend is unavailable or needs a configured restaurant. Start Spring Boot to load live metrics.' })) }, []); return state }
function MetricCard({ label, value, type, note, warning }) { return <article className={`metric-card ${warning ? 'metric-warning' : ''}`}><div className="metric-top"><span>{label}</span>{warning && <span className="signal-dot" />}</div><strong>{value == null ? <span className="skeleton-value" /> : formatValue(value, type)}</strong><small>{note}</small></article> }
function formatValue(value, type) { if (type === 'currency') return `$${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; if (type === 'percent') return `${Number(value || 0).toFixed(1)}%`; return value || 0 }
function Analytics({ title, eyebrow }) { const { data, loading } = useDashboardData(); return <><PageIntro eyebrow={eyebrow} title={title} description="Revenue, historical dish costs, and operational expenses in one view." /><section className="metric-grid compact"><MetricCard label="Revenue" value={loading ? null : data?.totalRevenue} type="currency" note="selected period" /><MetricCard label="Expenses" value={loading ? null : data?.totalExpenses} type="currency" note="selected period" /><MetricCard label="Profit margin" value={loading ? null : data?.profitMarginPercentage} type="percent" note="of revenue" /><MetricCard label="Food cost" value={loading ? null : data?.foodCostPercentage} type="percent" note="of revenue" /></section><section className="chart-grid"><ChartPanel title="Sales by dish" subtitle="Dish-level sales series will appear here."><EmptyChart /></ChartPanel><ChartPanel title="Inventory trend" subtitle="Inventory history will appear here."><EmptyChart /></ChartPanel></section></> }
function ResourcePage({ resource }) { const title = resource[0].toUpperCase() + resource.slice(1); const [items, setItems] = useState(null); const [error, setError] = useState(null); useEffect(() => { const date = new Date().toISOString().slice(0, 10); if (resource === 'expenses' && !restaurantId) { setError('Set VITE_RESTAURANT_ID to load live expenses.'); return } const query = resource === 'expenses' ? `?restaurantId=${restaurantId}&startDate=${date}&endDate=${date}` : ''; api.get(`/${resource}${query}`).then(r => setItems(r.data)).catch(() => setError('Connect the Spring Boot API to load live records.')) }, [resource]); return <><PageIntro eyebrow="Workspace" title={title} description={`Manage your ${resource} with data from the restaurant backend.`} action={`Add ${resource.slice(0, -1)}`} /><div className="data-panel">{error ? <ApiNotice message={error} /> : items === null ? <LoadingRows /> : items.length === 0 ? <EmptyState title={`No ${resource} yet`} text="Records will appear here as soon as they are created through the connected API." /> : <DataTable items={items} resource={resource} />}</div></> }
function DataTable({ items, resource }) { const keys = Object.keys(items[0] || {}).slice(0, 5); return <div className="table-wrap"><table><thead><tr>{keys.map(key => <th key={key}>{key.replace(/([A-Z])/g, ' $1')}</th>)}</tr></thead><tbody>{items.map((item, i) => <tr key={item.id || i}>{keys.map(key => <td key={key}>{String(item[key] ?? '—')}</td>)}</tr>)}</tbody></table><p className="table-caption">Showing live {resource} returned by the API.</p></div> }
function ChartPanel({ title, subtitle, children }) { return <article className="chart-panel"><div className="panel-heading"><div><h3>{title}</h3><p>{subtitle}</p></div><button className="more-button" aria-label={`More ${title}`}>···</button></div>{children}</article> }
function EmptyChart() { return <div className="empty-chart"><ResponsiveContainer width="100%" height={170}><AreaChart data={[]}><CartesianGrid stroke="#edf0e9" vertical={false} /><XAxis dataKey="date" hide /><YAxis hide /><Tooltip /></AreaChart></ResponsiveContainer><BarChart3 size={24} /><span>No series data yet</span></div> }
function BreakdownChart({ data }) { if (!data.length) return <EmptyChart />; return <div className="empty-chart"><BarChart3 size={24} /><span>{data.length} live categories available</span></div> }
function ApiNotice({ message }) { return <div className="api-notice"><Lightbulb size={18} /><span>{message}</span></div> }
function LoadingRows() { return <div className="loading-block"><span /><span /><span /></div> }
function EmptyState({ title, text }) { return <div className="empty-state"><ClipboardList size={25} /><h3>{title}</h3><p>{text}</p></div> }
function ComingSoon({ title, icon: Icon }) { return <div className="coming-soon"><span className="coming-icon"><Icon size={30} /></span><span className="eyebrow">Planned module</span><h1>{title}</h1><p>This workspace is ready for the next implementation step. No placeholder data is shown.</p></div> }
